
export const metadata = {
  title: "Home | Next Movies",
  description: "The Best Movies on the Best Frameworks Generated by Next.js",
};

export default function Page() {
  return (
    <div>
      <h1>Hello!</h1>
    </div>
  );
}